theme = "doriansPortfolio"
languageCode = "en-us"
baseurl = "https://example.com"
title = "Dorian"


[params]
  name = "Dorian"
  description = "Portfolio site of Dorian."
  author = "Dorian"
  authorEmail = "hello@dorian.im"
  authorImage = "/photo.png"
  autoDarkMode = true

  copyright = "Copyright © 2021 - Dorian Zedler · All rights reserved · "
  githubHref = "https://github.com/dorianim/portfolio"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey 👋 I'm Dorian"
  tagline = "Speedclimber and software developer"
  contact = "mailto:hello@dorian.im"

[[params.homepage.heroMenu]]
  icon = "fas fa-envelope"
  text = "Contact me"
  href = "mailto:hello@dorian.im"

[[params.homepage.heroMenu]]
  icon = "fab fa-gitlab"
  text = "blue.code"
  href = "https://itsblue.dev/dorian"

[[params.homepage.heroMenu]]
  icon = "fab fa-github"
  text = "GitHub"
  href = "https://github.com/dorianim"
  
[[params.homepage.heroMenu]]
  icon = "fab fa-instagram"
  text = "Instagram"
  href = "https://instagram.com/dorian.cpp"

[[params.homepage.gallery]]
  image = "/speedClimbing.jpg"
  #text = "More about Speedclimbing"
  #href = "https://speedclimbing.org"

[[params.homepage.gallery]]
  image = "/scStwIcon.png"
  text = "More about the ScStw"
  href = "https://itsblue.de/scstw"

[[params.homepage.gallery]]
  image = "/blueRockIcon.png"
  text = "More about blueROCK"
  href = "https://itsblue.de/apps/bluerock"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"