theme = "doriansPortfolio"
languageCode = "en-us"
baseurl = "https://example.com"
title = "Dorian"


[params]
  name = "Dorian"
  description = "Portfolio site of Dorian."
  author = "Dorian"
  authorEmail = "mail@dorian.im"
  authorImage = "/photo.png"
  autoDarkMode = true

  copyright = "Copyright © 2021 - Dorian Zedler · All rights reserved"
  gitHubHref = "https://github.com/dorianim/portfolio"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey 👋 I'm Dorian"
  tagline = "Speedclimber and software developer"
  #description = "Develop functional user interfaces and provide a valuable experience to customers."
  contact = "mailto:hello@dorian.im"

[[params.homepage.heroMenu]]
  icon = "fas fa-envelope"
  text = "Contact me"
  href = "mailto:hello@dorian.im"

[[params.homepage.heroMenu]]
  icon = "fab fa-github"
  text = "GitHub"
  href = "https://github.com/dorianim"
  
[[params.homepage.heroMenu]]
  icon = "fab fa-instagram"
  text = "Instagram"
  href = "https://instagram.com/dorian.cpp"

[[params.homepage.gallery]]
  image = "/speedClimbing.jpg"
  text = "More about Speedclimbing"
  href = "https://speedclimbing.org"

[[params.homepage.gallery]]
  image = "/scStwIcon.png"
  text = "More about the ScStw"
  href = "https://itsblue.de/scstw"

[[params.homepage.gallery]]
  image = "/blueRockIcon.png"
  text = "More about blueROCK"
  href = "https://itsblue.de/apps/bluerock"

[params.homepage.resume]
  skills = ["Visual Design", "Product Development"]

[[params.homepage.resume.work]]
  name = "Netzint GmbH"
  role = "Trainee"
  duration = "Nov 2019 - Apr 2021"

[[params.homepage.resume.work]]
  name = "Codewerk GmbH"
  role = "Intern"
  duration = "Jan 2021 - Feb 2021"

[[params.homepage.resume.courses]]
  name = "Design Principles"
  provider = "UX Academy"
  duration = "Nov 2019 - Jan 2020"

[params.homepage.social]
  github = "https://github.com/"
  instagram = "https://instagram.com/"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"