theme: "doriansPortfolio"
languageCode: "en"
baseurl: "https://dorian.im"
title: "Dorian"
defaultContentLanguage: en

params:
  name: "Dorian"
  author: "Dorian"
  authorEmail: "hello@dorian.im"
  autoDarkMode: true

  githubHref: "https://github.com/dorianim/portfolio"
  favicon: "favicon.ico"

  accentColor: "blue"

# syntax highlight settings
markup:
  highlight:
    style: "dracula"
  goldmark:
    renderer:
      unsafe: true

languages: 
  de:
    languageName: ":de:"
    params:
      description: "Portfolio von Dorian."
      copyright: "Copyright © 2021 - Dorian Zedler · Alle Rechte vorbehalten · "
      
  en:
    languageName: ":uk:"
    params:
      description: "Portfolio site of Dorian."
      copyright: "Copyright © 2021 - Dorian Zedler · All rights reserved · "