theme: "doriansPortfolio"
languageCode: "en-us"
baseurl: "https://dorian.im"
title: "Dorian"
defaultContentLanguage: en


params:
  name: "Dorian"
  description: "Portfolio site of Dorian."
  author: "Dorian"
  authorEmail: "hello@dorian.im"
  autoDarkMode: true

  copyright: "Copyright © 2021 - Dorian Zedler · All rights reserved · "
  githubHref: "https://github.com/dorianim/portfolio"
  favicon: "favicon.ico"

  accentColor: "blue"

# syntax highlight settings
markup:
  highlight:
    style: "dracula"
  goldmark:
    renderer:
      unsafe: true

languages: 
  de:
    title: "Dorian"
  en:
    title: "Dorian"