name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: klakegg/hugo:ext-alpine-ci
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: build
        run: npm i && hugo build --minify

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
          
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public